LOG_DIR: 'logs/camcalib/'
EXP_NAME: 'pano_real_r50_pretrained'
SEED_VALUE: -1
METHOD: 'pano'
RUN_TEST: False
PROJECT_NAME: 'camcalib'
DATASET:
  BATCH_SIZE: 4
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  IMG_RES: 224
  TRAIN_DS: pano
  VAL_DS: pano
OPTIMIZER:
  TYPE: 'adam'
  LR: 1e-3
  WD: 0.0
TRAINING:
  RESUME: null
  PRETRAINED: '/ps/scratch/mkocabas/developments/cvpr2021_projects/pare/logs/camcalib/pano_dataset_r50/03-02-2021_19-13-59_pano_dataset_r50_train/tb_logs/0/checkpoints/epoch=7.ckpt'
  MAX_EPOCHS: 30
  SAVE_IMAGES: True
  LOG_SAVE_INTERVAL: 50
  LOG_FREQ_TB_IMAGES: 2000
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
MODEL:
  BACKBONE: 'resnet50'
  NUM_FC_LAYERS: 2
  NUM_FC_CHANNELS: 1024
  LOSS_VFOV_WEIGHT: 1.0
  LOSS_PITCH_WEIGHT: 1.0
  LOSS_ROLL_WEIGHT: 1.0